# Generated by Django 5.1.4 on 2025-01-30 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_rename_dob_patient_date_of_birth_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.login'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.hospital'),
        ),
    ]
