# Generated by Django 5.1.4 on 2025-02-01 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_doctor_login_id_alter_doctor_hospital_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_id', to='medico.login'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_id', to='medico.login'),
        ),
    ]
