# Generated by Django 5.1.4 on 2025-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_alter_doctor_hospital_id_alter_doctor_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
