# Generated by Django 5.1.4 on 2025-02-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0006_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='specialization',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
