# Generated by Django 5.1.4 on 2025-02-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0008_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
