
# Generated by Django 5.1.4 on 2025-02-08 05:03

# Generated by Django 5.1.4 on 2025-02-07 06:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0011_alter_appointment_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(max_length=10),
        ),
    ]
