# Generated by Django 5.1.4 on 2025-02-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0016_alter_appointment_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
