# Generated by Django 5.1.4 on 2025-02-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0017_doctor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
