# Generated by Django 5.1.4 on 2025-02-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0018_remove_doctor_status_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
