# Generated by Django 5.1.4 on 2025-02-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0019_remove_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
