# Generated by Django 5.1.4 on 2025-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0021_appointment_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
