# Generated by Django 5.1.4 on 2025-02-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0021_alter_appointment_date_alter_appointment_patient_id_and_more'),
        ('medico', '0022_alter_appointment_prescription'),
    ]

    operations = [
    ]
