# Generated by Django 5.1.4 on 2025-02-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0022_alter_appointment_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
