# Generated by Django 5.1.4 on 2025-02-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0023_alter_appointment_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='specialization',
        ),
    ]
