# Generated by Django 5.1.4 on 2025-02-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0023_merge_20250212_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
