# Generated by Django 5.1.4 on 2025-02-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0024_alter_appointment_date_alter_appointment_time'),
        ('medico', '0024_remove_patient_specialization'),
    ]

    operations = [
    ]
