# Generated by Django 5.1.4 on 2025-02-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0024_remove_patient_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='MRI',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
