# Generated by Django 5.1.4 on 2025-02-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0028_alter_patient_mri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='MRI',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
