# Generated by Django 5.1.4 on 2025-02-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0025_merge_20250212_1459'),
        ('medico', '0029_alter_patient_mri'),
    ]

    operations = [
    ]
