# Generated by Django 5.1.4 on 2025-02-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0029_alter_patient_mri'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('from_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_hospital', to='medico.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.patient')),
                ('to_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_hospital', to='medico.hospital')),
            ],
        ),
    ]
