# Generated by Django 5.1.4 on 2025-02-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0030_patienttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hsp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.hospital'),
        ),
    ]
