# Generated by Django 5.1.4 on 2025-03-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0031_patient_hsp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hsp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.hospital'),
        ),
    ]
