# Generated by Django 5.1.4 on 2025-02-13 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0031_rename_patient_id_appointment_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='paitent_id', to='medico.login'),
        ),
    ]
