# Generated by Django 5.1.4 on 2025-03-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0032_alter_patient_hsp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttransfer',
            name='from_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_hospital', to='medico.hospital'),
        ),
    ]
