# Generated by Django 5.1.4 on 2025-02-13 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0032_alter_appointment_patientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patientid',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paitent_id', to='medico.login'),
        ),
    ]
