# Generated by Django 5.1.4 on 2025-02-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0030_patienttransfer'),
        ('medico', '0038_alter_patient_login_id'),
    ]

    operations = [
    ]
