# Generated by Django 5.1.4 on 2025-02-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0031_patient_hsp_id'),
        ('medico', '0039_merge_20250214_1501'),
    ]

    operations = [
    ]
