# Generated by Django 5.1.4 on 2025-03-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0033_alter_patienttransfer_from_hospital'),
        ('medico', '0040_merge_0031_patient_hsp_id_0039_merge_20250214_1501'),
    ]

    operations = [
    ]
