# Generated by Django 5.1.4 on 2025-03-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0034_remove_patient_hsp_id'),
        ('medico', '0041_merge_20250306_1238'),
    ]

    operations = [
    ]
