# Generated by Django 5.1.4 on 2025-03-09 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0043_rename_mri_patient_mr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_cat', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('hosp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosp_id', to='medico.login')),
                ('log_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_id', to='medico.login')),
            ],
        ),
    ]
