# Generated by Django 5.1.4 on 2025-03-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0044_ambulance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='ambulance_cat',
            new_name='ambulance_category',
        ),
    ]
